### ISSUE TITLE
Saving CoverArt as an Image

### ISSUE THREAD

**Issue by philipscott** [idcrook/shairport-sync-metadata-python#3]
Hi David. Great job on this ... works a treat, but I don't know how to use it to generate/save an actual image rather than asciiart. Do you have any examples or can you give me some guidance? I'm using it a Raspberry Pi btw.

**Comment by philipscott** [comment]
It's ok I worked out a way to do it. Probably not the right way, but it works :) I modified the packetize.py code to process the data when a PICT is received and then saving the data as a binary image.

**Comment by idcrook** [comment]
Yeah, the PICT is just a binary blob of an image. 

See [MQTT Flask](https://github.com/idcrook/shairport-sync-mqtt-display/blob/0f0b4779f2c38dd10e02e5615c6c3d49bac4df33/python-flask-socketio-server/app.py#L289) version sending over socket.io, and [displaying with dataurl](https://github.com/idcrook/shairport-sync-mqtt-display/blob/0f0b4779f2c38dd10e02e5615c6c3d49bac4df33/python-flask-socketio-server/templates/main.html#L152) in a webpage for additional ideas.
 
Closing
